"""initial schema

Revision ID: 7059debc9316
Revises: 
Create Date: 2026-06-24 13:35:43.449774
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7059debc9316'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=256), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('shares',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=False),
    sa.Column('principal_type', sa.String(length=32), nullable=False),
    sa.Column('principal_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'resource_id', 'principal_type', 'principal_id', name='uq_share')
    )
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shares_principal_id'), ['principal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shares_resource_id'), ['resource_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('oidc_sub', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_oidc_sub'), ['oidc_sub'], unique=False)

    op.create_table('saved_searches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_searches_user_id'), ['user_id'], unique=False)

    op.create_table('workspaces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_user_id', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('graph_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_snapshots_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_member')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('collection_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('blob_key', sa.String(length=512), nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('lane', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_lane'), ['lane'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_state'))
        batch_op.drop_index(batch_op.f('ix_jobs_source_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_lane'))

    op.drop_table('jobs')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_sources_content_hash'))
        batch_op.drop_index(batch_op.f('ix_sources_collection_id'))

    op.drop_table('sources')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('graph_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_snapshots_workspace_id'))

    op.drop_table('graph_snapshots')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_owner_user_id'))

    op.drop_table('workspaces')
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_searches_user_id'))

    op.drop_table('saved_searches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_oidc_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shares_resource_id'))
        batch_op.drop_index(batch_op.f('ix_shares_principal_id'))

    op.drop_table('shares')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
